{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}                # Hostname for your application
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}           # Path for ingress
            pathType: {{ .pathType }}   # Use Prefix path type
            backend:
              service:
                name: {{ include "mychart.fullname" . }}
                port:
                  number: {{ $.Values.service.port }}   # Kubernetes Service port
          {{- end }}
    {{- end }}
{{- end }}
