replicaCount: 2

image:
  repository: saud12345/java  
  tag: latest                 
  pullPolicy: IfNotPresent   

service:
  type: LoadBalancer            
  port: 80                    
  targetPort: 8080            

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx  
  hosts:
    - host: aba3efc3c3b4144399a32b0e70a2a823-1594324638.us-east-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix

resources: {}                            
