replicaCount: 2

image:
  repository: saud12345/java  
  tag: latest                 
  pullPolicy: Always

service:
  type: LoadBalancer            
  port: 80                    
  targetPort: 8080            

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx  
  hosts:
    - host: a8787003711d14a7380e8a6fbb3571c4-518826175.us-east-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix

resources: {}                            
