name: 'AWS Configure'
description: 'Configure AWS credentials using assumed role'
inputs:
  role-arn:
    description: 'The ARN of the role to assume'
    required: true
  region:
    description: 'The AWS region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.region }}
