name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-configure
        with:
          role-arn: arn:aws:iam::099199746132:role/terraform-assume-role
          region: 'us-east-1'

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker build -t java-app-saud .
          docker tag java-app-saud:latest 099199746132.dkr.ecr.us-east-1.amazonaws.com/java-app-saud:latest
          docker push 099199746132.dkr.ecr.us-east-1.amazonaws.com/java-app-saud:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.0'

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-configure
        with:
          role-arn: arn:aws:iam::099199746132:role/terraform-assume-role
          region: 'us-east-1'

      - name: Deploy to EKS using Helm
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1
          ./deploy.sh
